### PR TITLE
Enhance coverage

### PR DESCRIPTION
**Pull request by eweisger**
For reviewing the removal of all cython solver tests.

### CODE REVIEW

**Comment by seanebum** [comment]
In test_all_solvers, why are the test signatures commented out?

**Comment by eweisger** [comment]
That might have been from when I was trying to find the divide by zero bug and I simply forgot to remove them.

**Comment by eweisger** [comment]
I have removed the comments in test_all_solvers and updated the branch.

**Comment by seanebum** [comment]
Awesome, looks good to me!

**Comment by seanebum** [comment]
If we re-run coverage, will that bring the coverage back up some? 26% looks pretty rough!

**Comment by eweisger** [comment]
I just re-ran the coverage on my end and it is saying 65%. It might have gone down because I am no longer testing the cython solver but the code for it is still there.

**Comment by briandrawert** [comment]
Is it possible for you to remove the cython solver from the code based that is counted?

**Comment by eweisger** [comment]
I believe I was able to exclude the cython solver files in the coverage and updated the branch again. The coverage is still 65%.

**Pull request merged**
