### PR TITLE
C solvers

### PR DESCRIPTION
**Pull request by Thisisnotdalton**
Changed SSACSolver so that it does not need to be recompiled for each simulation of the same model. The SSACSolver now has a constructor which requires the model to be provided. The instance of the solver will then set up directories to store the C++ files in and compile said files before the solver may be used.

This means that a different instance of the SSACSolver must be generated for each different model, but the solver does not need to recompile for simple changes to the number of trajectories, timesteps, end time, or random seed.

The SSACSolver constructor additionally takes parameters specifying an output directory for the C++ files as well as a Boolean flag for whether or not to delete the files after the solver instance is removed. If no output directory is specified, the solver defaults to using a temporary directory and sets the delete flag to true. When the SSACSolver instance is deleted, it should automatically remove  directories as needed; however, the temporary directories still seem to persist until a computer reboot in the event of a kernel restart in Jupyter notebooks.

Comparing the SSACSolver to the StochKit solvers suggest that it performs significantly faster now that it only compiles the simulation file once.

### CODE REVIEW

**Comment by briandrawert** [comment]
4.  Need example notebook with directions on how to use this solver.

**Comment by briandrawert** [comment]
Be sure that "model.run()" works

**Comment by briandrawert** [comment]
```
brian@james:~/research/GillesPy2/test$ python3 time_solvers.py
  File "time_solvers.py", line 41
    for i in trange(trials, desc = f'Model: {model.name}, Solver: {solver.name}, Trajectories: {trajectory}'):
                                                                                                           ^
SyntaxError: invalid syntax
brian@james:~/research/GillesPy2/test$ python3 --version
Python 3.5.2
```

**Comment by Thisisnotdalton** [comment]
The error with the f-string in time_solvers.py is because it is a Python 3.6+ convention. I will change this to the more prevalent .format() method.

**Comment by briandrawert** [comment]
This looks good to merge.  @seanebum, please review and comment or merge.

**Comment by briandrawert** [comment]
Need to remove warning:
`WARNING:root:Unable to use Cython optimized SSA:
Error:No module named 'pyximport'`

**Comment by briandrawert** [comment]
Warning moved to issue #17

**Pull request merged**
