### PR TITLE
C solvers

### PR DESCRIPTION
**Pull request by JustJackson**
This is Dalton's new C++ Solver. Primary purpose of PR is fold into the testing battery class. Discussion on Apr. 3rd Lab Meeting.

### CODE REVIEW

**Comment by Thisisnotdalton** [comment]
This should be fine to merge in. The __init__.py should label it as SSACSolver in gillespy2. The only issues you may encounter are if you're running multiple instances of it in parallel since I've not yet changed the solver to generate uniquely named C++ files.

**Comment by briandrawert** [comment]
Please add test script in a 'test' directory that will execute this solver.

**Comment by briandrawert** [comment]
I got this on OSX:
`$ make
g++ -c -o model.o model.cpp -c -Wall -O3
model.cpp:9:22: error: no member named 'make_unique' in namespace 'std'
    species = std :: make_unique<Species[]>(number_species);
              ~~~~~~ ^
model.cpp:9:34: error: 'Species' does not refer to a value
    species = std :: make_unique<Species[]>(number_species);
                                 ^
./model.h:11:10: note: declared here
  struct Species{
         ^
model.cpp:9:42: error: expected expression
    species = std :: make_unique<Species[]>(number_species);
                                         ^
model.cpp:15:24: error: no member named 'make_unique' in namespace 'std'
    reactions = std :: make_unique<Reaction[]>(number_reactions);
                ~~~~~~ ^
model.cpp:15:36: error: 'Reaction' does not refer to a value
    reactions = std :: make_unique<Reaction[]>(number_reactions);
                                   ^
./model.h:17:10: note: declared here
  struct Reaction{
         ^
model.cpp:15:45: error: expected expression
    reactions = std :: make_unique<Reaction[]>(number_reactions);
                                            ^
model.cpp:18:44: error: no member named 'make_unique' in namespace 'std'
      reactions[i].species_change = std :: make_unique<int[]>(number_species);
                                    ~~~~~~ ^
model.cpp:18:59: error: expected '(' for function-style cast or type construction
      reactions[i].species_change = std :: make_unique<int[]>(number_species);
                                                       ~~~^
8 errors generated.
make: *** [model.o] Error 1
`

**Comment by JustJackson** [comment]
I think it is important to note that we had to change the makefile to have this compile. Anecdotal, worked on Dalton's machine, It worked on mine from terminal but not from Jupyter, and Sean had to change it for it to work at all on his machine. I'll test it on my mac and maybe I'll spin up a windows machine tonight to check it before the meeting, but I'm fairly certain it's good for Linux.

**Pull request merged**
