### PR TITLE
Changed 'is' to '==', 'is not' to '!=' when comparing to non-singletons

### PR DESCRIPTION
**Pull request by jdreeve**
The reason unpickled results objects were treating time as a species was that the test in _plot_iterate (results.py line 21) was as follows:

if species is not time:

This is an identity test, not an equality test. The correct test is:

if species != time:

I made this change to all comparisons to non-singletons.

### CODE REVIEW

**Comment by briandrawert** [comment]
This is great!  Can you pull from develop to resolve the conflicts?

**Comment by jdreeve** [comment]
Pulled from develop to correct conflicts and re-tested.

**Comment by briandrawert** [comment]
Do you have a notebook or script that you are testing with?  Ideally, we would add a unit test to prevent a reversion in the future too.

**Comment by jdreeve** [comment]
I tested using a notebook, but it's not in a state that would make sense to a user (or indeed anyone else). Do you want me to add a tutorial notebook on pickling, and concatenating Results, when I implement that?

What exactly that would that unit test cover?

**Pull request merged**
